// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOhUG6cYeYJJgLPzqbXkag1hjNBBT7tro',
    appId: '1:678222317674:web:a75d68734f9916d0612213',
    messagingSenderId: '678222317674',
    projectId: 'bricksapplication-768ac',
    authDomain: 'bricksapplication-768ac.firebaseapp.com',
    storageBucket: 'bricksapplication-768ac.firebasestorage.app',
    measurementId: 'G-ZX1C3MR0N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBjsBzGaqQSZzyfNZzhjDJx4UombfNV8E',
    appId: '1:678222317674:android:1080cbcea46dddad612213',
    messagingSenderId: '678222317674',
    projectId: 'bricksapplication-768ac',
    storageBucket: 'bricksapplication-768ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5r3dYMKvkgq__9e2veFIEiDTGh44NocE',
    appId: '1:678222317674:ios:1495ae9146eadc36612213',
    messagingSenderId: '678222317674',
    projectId: 'bricksapplication-768ac',
    storageBucket: 'bricksapplication-768ac.firebasestorage.app',
    iosBundleId: 'com.example.bricksApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5r3dYMKvkgq__9e2veFIEiDTGh44NocE',
    appId: '1:678222317674:ios:1495ae9146eadc36612213',
    messagingSenderId: '678222317674',
    projectId: 'bricksapplication-768ac',
    storageBucket: 'bricksapplication-768ac.firebasestorage.app',
    iosBundleId: 'com.example.bricksApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOhUG6cYeYJJgLPzqbXkag1hjNBBT7tro',
    appId: '1:678222317674:web:de7037f63b80e11b612213',
    messagingSenderId: '678222317674',
    projectId: 'bricksapplication-768ac',
    authDomain: 'bricksapplication-768ac.firebaseapp.com',
    storageBucket: 'bricksapplication-768ac.firebasestorage.app',
    measurementId: 'G-PQ4XDEW5JT',
  );
}
